server:
  port: 8090

# datasourceProperties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSl=false&serverTimeZone=HongKong
    type: com.zaxxer.hikari.HikariDataSource
# pool池
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
# 模板引擎
  thymeleaf:
    cache: false


  mail:
    protocol: smtp
    password: qvwhbgvnhvnqejda
    username: 1779178166@qq.com
    host: smtp.qq.com


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.nowcoder.comunity:
      debug


community:

   domain: http://localhost:8090
   uploadPath: C:\Users\刘逸菲\Desktop\Java\header
